### ISSUE TITLE
sortBy() does not work with umlauts or accents

### ISSUE THREAD

**Issue by Pasley70** [bastianallgeier/kirby#36]
I want to sort german-language pages by a data field named "Last Name". Although the correct language settings have been made (locale "de_DE" or "de_DE.UTF8") the sorting is incorrect.
Example: Br stands before Bä, Dv stands before Dé. A sorting method like "SORT_LOCALE_STRING" would be helpful. (Linux and Mac, both with Kirby 2.1.2, PHP 5.6).

**Comment by bastianallgeier** [comment]
I found out that this is actually a pretty serious issue in PHP. There are some workarounds, but I didn't find any good one for multiple array sorting so far. I will keep on it, but can't promise that I will have a fix for 2.2.

**Comment by bastianallgeier** [comment]
I moved it to the correct issue btw :) https://github.com/getkirby/kirby/issues/320
